<a href="https://colab.research.google.com/github/remigiuszsek/Python-studia/blob/main/%C4%87w7_pdf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Biblioteka numpy cz 2

In [ ]:
import numpy as np

1.1. Operacje arytmetyczne

In [ ]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)
print(b)
c = a - b
print(c)
print(b**2)
print('To jest a: ')
print(a)
a+=b
print(a)
a-=b
print(a)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
To jest a: 
[20 30 40 50]
[20 31 42 53]
[20 30 40 50]


1.2 Operacje na osiach

In [ ]:
d = np.arange(12).reshape(3,4)
print(d)
print(d.sum())
print(d.sum(axis=0))
print(d.min(axis=1))
print(d.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


1.3. Mnożenie macierzy

In [ ]:
a = np.arange(3)
print(a)
b = np.arange(3)
print(b)
print(np.dot(a,b))

[0 1 2]
[0 1 2]
5


1.4. Operacje na tablicach różnej dokładności (upcasting)

In [ ]:
a = np.ones(3, dtype=np.int32)
print(a)
print(a.dtype.name)
b = np.linspace(0,np.pi,3)
print(b)
print(b.dtype.name)
c = a + b
print(c)
print(c.dtype.name)
d = np.exp(c*1j)
print(d)
print(d.dtype.name)

[1 1 1]
int32
[0.         1.57079633 3.14159265]
float64
[1.         2.57079633 4.14159265]
float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


Zad. 1. Utwórz dwie macierze 1x3 różnych wartości a następnie wykonaj operację mnożenia.

In [ ]:
a = np.arange(2,5).reshape(1,3)
print(a)
b = np.arange(3,6).reshape(3,1)
print(b)
print(a*b)

[[2 3 4]]
[[3]
 [4]
 [5]]
[[ 6  9 12]
 [ 8 12 16]
 [10 15 20]]


Zad. 2. Utwórz macierz 3x3 oraz 4x4 i znajdź najniższe wartości dla każdej kolumny i każdego
rzędu.

In [ ]:
a = np.arange(9).reshape(3,3)
print(a)
b = np. arange(16).reshape(4,4)
print(b)
print(a.min(axis=0))
print(a.min(axis=1))
print(b.min(axis=0))
print(b.min(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2]
[0 3 6]
[0 1 2 3]
[ 0  4  8 12]


Zad. 3. Wykorzystaj macierze z zadania pierwszego i wykonaj iloczyn macierzy.

In [ ]:
a = np.arange(2,5).reshape(1,3)
print(a)
b = np.arange(3,6).reshape(3,1)
print(b)
print(np.dot(a,b))

[[2 3 4]]
[[3]
 [4]
 [5]]
[[38]]


Zad. 4. Utwórz dwie macierze 1x3 gdzie pierwsza z nich będzie zawierała liczby całkowite, a druga
liczby rzeczywiste. Następnie wykonaj na nich operację mnożenia

In [ ]:
a = np.arange(3).reshape(3,1)
print(a)
b = np.arange(3, dtype=float).reshape(3,1)
print(b)
print(a*b)

[[0]
 [1]
 [2]]
[[0.]
 [1.]
 [2.]]
[[0.]
 [1.]
 [4.]]


2. Funkcje uniwersalne

In [ ]:
b = np.arange(3)
print(b)
print(np.exp(b))
print(np.sqrt(b))
c = np.array([2., -1., 4])
print(np.add(b, c))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]


Zad. 5. Utwórz macierz 2x3 różnych wartości a następnie wylicz sinus dla każdej z jej wartości i
zapisz do zmiennej “a”.

In [ ]:
x = np.arange(6).reshape(2,3)
print(x)
a = np.sin(x)
print(a)

[[0 1 2]
 [3 4 5]]
[[ 0.          0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]]


Zad. 6. Utwórz nową macierz 2x3 różnych wartości a następnie wylicz cosinus dla każdej z jej
wartości i zapisz do zmiennej “b”.

In [ ]:
a = np.arange(6).reshape(2,3)
print(a)
b = np.cos(a)
print(b)


[[0 1 2]
 [3 4 5]]
[[ 1.          0.54030231 -0.41614684]
 [-0.9899925  -0.65364362  0.28366219]]


Zad. 7 Wykonaj funkcję dodawania obu macierzy zapisanych wcześniej do zmiennych a i b.

In [ ]:
a = np.arange(6).reshape(2,3)
b = np.arange(3,9).reshape(2,3)
print(b)
print(np.add(a,b))

[[3 4 5]
 [6 7 8]]
[[ 3  5  7]
 [ 9 11 13]]


3. Iteracja tablic

In [ ]:
b = np.arange(6).reshape(3,2)
print(b)
for a in b:
  print(a)
c = np.arange(6).reshape(3,2)
print(c)
for a in c.flat:
  print(a)

[[0 1]
 [2 3]
 [4 5]]
[0 1]
[2 3]
[4 5]
[[0 1]
 [2 3]
 [4 5]]
0
1
2
3
4
5


Zad. 8. Wygeneruj macierz 3x3 i wyświetl w pętli każdy z rzędów.

In [ ]:
b = np.arange(9).reshape(3,3)
for a in b:
  print(a)

[0 1 2]
[3 4 5]
[6 7 8]


Zad. 9. Wygeneruj macierz 3x3 i wyświetl w pętli każdy element korzystając z opcji “spłaszczenia”
macierzy.

In [ ]:
a = np.arange(9).reshape(3,3)
for b in a.flat:
  print(b)

0
1
2
3
4
5
6
7
8


4. Przekształcenia

In [ ]:
b = np.arange(6)
print(b)
print(b.shape)
c = np.array([np.arange(3), np.arange(3), np.arange(3)])
print(c)
print(c.shape)

[0 1 2 3 4 5]
(6,)
[[0 1 2]
 [0 1 2]
 [0 1 2]]
(3, 3)


In [ ]:
b = np.arange(6)
print(b)
print(b.shape)
c = b.reshape((2,3))
print(c)
print(c.shape)
d = c.reshape((3,2))
print(d)
print(d.shape)
e = d.ravel()
print(e)
print(e.shape)
f = c.T
print(f)
print(f.shape)

[0 1 2 3 4 5]
(6,)
[[0 1 2]
 [3 4 5]]
(2, 3)
[[0 1]
 [2 3]
 [4 5]]
(3, 2)
[0 1 2 3 4 5]
(6,)
[[0 3]
 [1 4]
 [2 5]]
(3, 2)


Zad. 10. Wygeneruj macierz 9x9 a następnie zmień jej kształt. Jakie mamy możliwości i dlaczego?

In [ ]:
a = np.arange(81).reshape(9,9)
print(a)
b = a.reshape(3, 27)
print(b)
#Mamy możliwości, żeby z kształtu (9,9) zmienić jedynie na (3,27) i (27,3), ponieważ są to tylko dwa istniejące kształty, które wpasuje się idealnie 81 
#elementów

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26]
 [27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
  51 52 53]
 [54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77
  78 79 80]]


Zad. 11. Wygeneruj macierz płaską i przekształć ja na 3x4. Wygeneruj w ten sposób jeszcze
kombinacje 4x3 i 2x6. Spłaszcz każdą z nich i wyświetl wyniki. Czy są identyczne?

In [ ]:
a = np.arange(12)
print(a)
d = a.reshape(3,4)
print(d)
b = a.reshape(4,3)
print(b)
c = a.reshape(2,6)
print(c)
print('Spłaszczone: b i c')
print(b.ravel())
print(c.ravel())
print('Odp.: Tak, są identyczne')

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Spłaszczone: b i c
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Odp.: Tak, są identyczne
